on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test App
    runs-on:  ubuntu-latest
    env:
      BASE_URL: ${{secrets.BASE_URL}}
      DEFAULT_POSTS_RETURN: ${{secrets.DEFAULT_POSTS_RETURN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install --upgrade -r requirements.txt
      - run: pytest tests --alluredir=allure-results
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          DEFAULT_POSTS_RETURN: ${{secrets.DEFAULT_POSTS_RETURN}}

      - name: Download Allure
        if: always()
        run: |
            sudo apt-add-repository ppa:qameta/allure -y
            sudo apt-get update
            sudo apt-get install allure -y

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report


      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./allure-report


